defaults: &defaults
  app_name: "52jita"
  foot_html: "&copy; 52jita"
  domain: "52jita.net"
  admin_emails:
    - "feitian124@gmail.com"
  google_analytics_key: ""
  upload_url: "http://52jita.qiniudn.com"
  qiniu_bucket_domain: "52jita.qiniudn.com"
  qiniu_access_key: "z1WUAxjx4iMjmoRsiafvrgBR35_FsurLHKaUiL6b"
  qiniu_secret_key: "dI0BodvL1x2I9PpE9l2c4oRJXg4qunE_sYlUSWeq"
  qiniu_bucket: "52jita"
  qiniu_protocal: "http"
  email_server: "smtp.exmail.qq.com"
  email_sender: 'service@52jita.net'
  email_password: '52jita.net'
  faye_server: "http://127.0.0.1:8080/faye"
  faye_token: "123456"
  twitter_token: "uJ9fBa53SmqrHBqs1qq5cg"
  twitter_secret: "b9e9hbsa9sYYCqmW0kTyfALshclmkQX4kzTm8BBBTw"
  github_token: "207bd3415f6f42bcf8da"
  github_secret: "8d51636e1325cd4a0af78efe567a35f29d42096d"
  douban_token: "04fab3198986e6350ef0194c9c94b29f"
  douban_secret: "5c08eac53cfa1890"
  google_js_api_key: "ABQIAAAAC-ble-vmy_g7-Qvem5P86xTX2XchcwgyHzp4Xo0DHRAzt2aLjhQnflwIyCJBOWYCE_rFuUkE0qEmhw"
  google_custom_search_id: "016658237367474087615:WMX464284035"
  external_feed_url: "http://ruby-taiwan.org/topics/feed"
  external_feed_name: "Ruby Taiwan Group"
  twitter_id: "ruby_china"
  gravatar_proxy: "http://gravatar.com"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
